// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT4H2qPq2ZOrBBU7KrFNc-H8iSLxBj7wQ',
    appId: '1:274356033183:web:7940900c876357546bb4aa',
    messagingSenderId: '274356033183',
    projectId: 'workshopfirebase-56c67',
    authDomain: 'workshopfirebase-56c67.firebaseapp.com',
    storageBucket: 'workshopfirebase-56c67.firebasestorage.app',
    measurementId: 'G-3BRZ9DYYT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOOve1kCnvcJ0OGUFdRO5f33RZ-D6X8w0',
    appId: '1:274356033183:android:3f807abef13330e36bb4aa',
    messagingSenderId: '274356033183',
    projectId: 'workshopfirebase-56c67',
    storageBucket: 'workshopfirebase-56c67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiKEdAGhm4_r7DhAVsB88A96Wyv3jrHic',
    appId: '1:274356033183:ios:1727c0b38a4ee7d86bb4aa',
    messagingSenderId: '274356033183',
    projectId: 'workshopfirebase-56c67',
    storageBucket: 'workshopfirebase-56c67.firebasestorage.app',
    androidClientId: '274356033183-bbc2rr8dl3l8qbpfrbue2hjqckn9o2a6.apps.googleusercontent.com',
    iosClientId: '274356033183-hoce65mdbk25iroi1k7afr5nth5o02s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreWorkshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiKEdAGhm4_r7DhAVsB88A96Wyv3jrHic',
    appId: '1:274356033183:ios:1727c0b38a4ee7d86bb4aa',
    messagingSenderId: '274356033183',
    projectId: 'workshopfirebase-56c67',
    storageBucket: 'workshopfirebase-56c67.firebasestorage.app',
    androidClientId: '274356033183-bbc2rr8dl3l8qbpfrbue2hjqckn9o2a6.apps.googleusercontent.com',
    iosClientId: '274356033183-hoce65mdbk25iroi1k7afr5nth5o02s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreWorkshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT4H2qPq2ZOrBBU7KrFNc-H8iSLxBj7wQ',
    appId: '1:274356033183:web:3460f14dd85479716bb4aa',
    messagingSenderId: '274356033183',
    projectId: 'workshopfirebase-56c67',
    authDomain: 'workshopfirebase-56c67.firebaseapp.com',
    storageBucket: 'workshopfirebase-56c67.firebasestorage.app',
    measurementId: 'G-9MC871CVJQ',
  );
}
